enum_trailing_comma = false
fn_args_density = "Compressed"
fn_args_paren_newline = false
fn_brace_style = "PreferSameLine"
fn_return_indent = "WithArgs"
reorder_imports = true
single_line_if_else = true
struct_trailing_comma = "Never"
struct_lit_trailing_comma = "Never"
struct_lit_width = 50